<?php
namespace Gemvc\Stcms\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Filesystem\Filesystem;

class CacheClearCommand extends Command
{
    protected static $defaultName = 'cache:clear';
    protected static $defaultDescription = 'Clears the application cache (Twig, etc.).';

    protected function configure(): void
    {
        $this
            ->setName('cache:clear')
            ->setDescription('Clears the STCMS application cache.')
            ->setHelp('This command allows you to delete the cache files generated by the application, primarily for templates.');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $fs = new Filesystem();
        $cacheDir = rtrim(sys_get_temp_dir(), '/') . '/stcms_cache';

        $output->writeln('<info>Attempting to clear cache...</info>');

        if (!$fs->exists($cacheDir)) {
            $output->writeln('<comment>Cache directory not found. Nothing to clear.</comment>');
            return Command::SUCCESS;
        }

        try {
            $fs->remove($cacheDir);
            $output->writeln('<info>✅ Cache cleared successfully!</info>');
            return Command::SUCCESS;
        } catch (\Exception $e) {
            $output->writeln('<error>An error occurred while clearing the cache:</error>');
            $output->writeln('<error>' . $e->getMessage() . '</error>');
            return Command::FAILURE;
        }
    }
} 